// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 0.1
:manmanual: Gpkg Manual
:mansource: 0.1
:man-linkstyle: pass:[blue R < >]
= gpkg(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

gpkg - gpkg is an utility that creates GeoPackage from database spatial data.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*gpkg* [*-hvV*] _FILE_ _JSON_

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

gpkg is an utility that creates GeoPackage from database spatial data.

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-h*, *--help*::
  Show this help message and exit.

*-v*, *--verbose*::
  Verbose mode. Helpful for troubleshooting.

*-V*, *--version*::
  Print version information and exit.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

_FILE_::
  The GeoPackage output file

_JSON_::
  
+
JSON file containing export configuration :
+
{
+
  "datasource": {            /* source database configuration, all properties are required */
+
    "host": "that.host",  
+
    "port": 5432,
+
    "database": "that_db",
+
    "schema": "that_schema",
+
    "user": "mkeal",  
+
    "password": "azerty"  
+
  },
+
  "contents": [
+
    {
+
      "source": {                      /* configuration of source data to export*/
+
        "tableName": "that_table",     /* (*) name of the table containing features to export */
+
        "columns": ["height", "geom"], /* (*) list of the column names to export, must contain a geometry column */
+
        "filter": "height > 10",       /* filter query */
+
        "maxFeatures": 50              /* maximum number of features to export */
+
      },
+
      "geopackage": {                  /* configuration of geopackage data */
+
        "identifier": "stuff"          
+
        "srid": 4326,              
+
        "description": "so much stuff"      
+
      }
+
    }
+
  ]
+
}
+


// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
